name: Run lint and tests

on: [push, pull_request]

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '12'
  - run: npm install
  - run: npm lint
  - run: npm test
