# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint, Build and Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Test
        if: matrix.node-version == '22.x'
        run: npm run test:ci

      - name: Test
        if: matrix.node-version != '22.x'
        run: npm run test

      - name: 📊 Code Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: always() && matrix.node-version == '22.x'
        with:
          test-script: npm run test:ci
          coverage-file: report.json
          base-coverage-file: report-base.json
          skip-step: install
          annotations: 'failed-tests'
